mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path(''),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('scheduler/', include('scheduler.urls')),
]

mysite/polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id/results/', views.reesults, name="results"),
    path('<int:question_id/vote/', views.vote, name="vote")
]

mysite/scheduler/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('index/', views.indexPage, name="indexPage"),
]

mysite/polls/models.py
from django.db import models

# Create your models here.
class Question(models.Model):

    def __str__(self):
        return self.question_text

    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

class Choice(models.Model):

    def __str__(self):
        return self.question

    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

mysite/scheduler/models.py
from django.db import models

# Create your models here.

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Question
# Create your views here.

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    context = {'latest_question_list': latest_question_list}
    return render(request, 'polls/index.html', context)

def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/detail.html', {'question': question})

def reesults(request, question_id):
    response = "You're looking at results of question %s"
    return HttpResponse(response % question_id)

def vote(request, question_id):
    return HttpResponse("You are voting on questions %s", question_id)

mysite/scheduler/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import *
# Create your views here.

def index(request):
    return HttpResponse('You are in the schedulder main')


def indexPage(request):
    return render(request, 'scheduler/index.html')

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>
<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }}</li>
{% endfor %}
</ul>

mysite/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="/polls/{{ question.id }}/">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/scheduler/templates/scheduler/index.html
<html>
    <head></head>

    <body>
        <p>This is the index page render.</p>
    </body>
</html>